version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: baseball-api.app
    env_file:
      - ./app/.env
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    tty:
      true
    networks:
      - baseball-batch_default
      - baseball-api_default

networks:
  baseball-batch_default:
    external: true
  baseball-api_default:
    external: true
