version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run:
          name: check node version
          command: | 
            node --version
      - run:
          name: check npm version
          command: | 
            npm -v

workflows:
  Deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
                - circleci-project-setup
