version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run:
          name: Install caprover cli
          command: | 
            sudo npm install -g caprover
      - run:
          name: Check caprover version
          command: | 
            sudo caprover --version

workflows:
  Deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
                - circleci-project-setup
